server:
  port: 8083
spring:
  application:
    name: search-service
  rabbitmq:
    host: 192.168.80.130
    username: leyou
    password: leyou
    virtualHost: /leyou
    template:
      exchange: leyou.item.exchange
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.80.130:9300
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #过期时间
